# Generated by Django 5.1.5 on 2025-01-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_datecompleted_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dateCompleted',
            new_name='date_completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='impotant',
            new_name='important',
        ),
    ]
